import type { Metadata } from "next";
// Якщо імпорт geist/font не працює, використайте інший Google Font або стандартний шрифт.
// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ['latin'] });
import "./globals.css";

// const geistSans = GeistSans;
// const geistMono = GeistMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
